services:
  frontend:
    build: ../PI_Primavera_Frontend
    container_name: events_frontend
    ports:
      - "5173:5173"
    networks:
      - events_network
    volumes:
      - ../PI_Primavera_Frontend/src:/app/src
      - ../PI_Primavera_Frontend/public:/app/public
    depends_on:
      - backend

  backend:
    build: .
    container_name: events_backend
    ports:
      - "5001:5000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=events_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - events_network
    volumes:
      - ./src:/app/src

  postgres:
    image: postgres:16-alpine
    container_name: events_postgres
    environment:
      - POSTGRES_DB=events_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - events_network

networks:
  events_network:
    driver: bridge

volumes:
  postgres_data:
